title: The Miller Essentials
author: Amy Miller
email: aegmiller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn about why I love essential oils and Young Living.

# social links
twitter_username: @jmumama
github_username:  aegmiller

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
